import type { Locale } from './i18n'

const en = {
  nav: { destinations: 'Destinations', regions: 'Regions', carFree: 'Car-free', pass: 'Swiss Travel Pass', carRental: 'Car rental', menu: 'Menu', close: 'Close' },
  affiliate: 'Some hotel links are affiliate links. That changes neither the price you pay nor our selection.',
  affiliateShort: 'Some hotel links are affiliate links.',
  methodology: 'Methodology',
  quickAnswer: 'Quick answer',
  metres: 'm',
  closedOffSeason: 'Closed off-season',
  checkAvailability: 'Check availability',
  seePage: 'See the page',
  inPreparation: 'Coming soon',
  open: 'Open',
  reduced: 'Partly closed',
  closed: 'Closed',
  months: ['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D'],
  choice: { village: 'Village', forWhom: 'Who it suits', legendFull: 'Filled square = stronger on this criterion', legendBest: 'Best pick for the criterion' },
  pass: { section: 'Section', coverage: 'Swiss Travel Pass', included: 'Included', discount25: '25% off', discount50: '50% off', fare: '2026 fare · CHF', without: 'Without pass', with: 'With pass', withoutShort: 'Without', withShort: 'With' },
  booking: { where: 'Where', checkin: 'Check-in', checkout: 'Check-out', search: 'See the hotels', nights: 'nights', trust: 'Your dates apply to every hotel and to the live map below.' },
  sell: {
    liveMap: 'Hotels in {place}, live prices',
    liveMapSub: 'Pick your dates above, then click a marker to see the price and book on the partner site.',
    seeAll: 'See every hotel in {place}',
    checkPrices: 'Check prices',
    stickyTitle: 'Hotels in {place}',
    stickyCta: 'See prices',
    ctaBandTitle: 'Found your area? Check what is still free in {place}.',
    ctaBandText: 'Prices and availability change daily in the Alps, especially in July, August and over Christmas.',
    hotelsIn: 'Hotels in {place}',
    moreForTrip: 'More for your trip',
    how: [
      { t: 'Pick the right village', d: 'Each page tells you where to sleep and why, with the numbers that decide it.' },
      { t: 'Compare on the map', d: 'The live map shows the places to stay with prices for your dates.' },
      { t: 'Book on the partner site', d: 'You book on Booking.com, Expedia or others at their price. We may earn a commission.' },
    ],
    howTitle: 'How it works',
    featured: 'Featured guide',
    readGuide: 'Read the guide',
    popular: 'Popular searches',
    all: 'All',
    carFreeFilter: 'Car-free',
    close: 'Close',
    hotels: { all: 'All', tiers: { budget: 'Budget', mid: 'Mid-range', premium: 'Top end' }, from: 'From', perNight: '/ night', average: 'Average seen', seasonAvg: { summer: 'Summer average', winter: 'Winter average' }, noSeason: 'No price found for this season on our sample dates', noPrice: 'No price collected on our sample dates', cta: 'Check prices', stars: 'stars', title: '{count} hotels in {place}, from budget to top end', note: 'Prices: lowest and average nightly rate seen on Booking.com for 2 adults and 1 room, on {winter} winter dates and {summer} summer dates, collected on {date}. They are indicative, the real price depends on your dates. Hotel facts come from each hotel’s own website.' },
    seasons: { summer: 'Summer', winter: 'Winter', title: 'Summer or winter?', base: 'Where to stay this season', sub: 'Pick a season, or set your dates above: prices and advice follow.' },
    doing: { kinds: { walk: 'On foot', ride: 'Up the mountain', local: 'Typical here', table: 'Where to eat' } },
    onThisPage: { map: 'Map', overview: 'Overview', hotels: 'Hotels', areas: 'Areas', doing: 'What to do', pass: 'Swiss Travel Pass', seasons: 'Seasons', carFree: 'Car-free', practical: 'Practical', faq: 'FAQ', choice: 'Compare', sheet: 'Villages', verdict: 'Verdict' },
  },
  mapNote: 'Map provided by Stay22. Bookings made from this map may earn us a commission.',
  mapLoad: 'Show the map',
  footer: {
    regions: 'Regions',
    destinations: 'Destinations',
    guides: 'Practical guides',
    about: 'About',
    affiliation: 'Affiliate links',
    legal: 'Legal notice',
    privacy: 'Privacy and cookies',
    independent: 'Independent guide, not affiliated with the Swiss authorities or Switzerland Tourism.',
  },
  notFound: { title: 'Page not found', text: 'This page does not exist or has moved.', home: 'Back to the home page' },
}

export type Dict = typeof en

const fr: Dict = {
  nav: { destinations: 'Destinations', regions: 'Régions', carFree: 'Sans voiture', pass: 'Swiss Travel Pass', carRental: 'Location de voiture', menu: 'Menu', close: 'Fermer' },
  affiliate: 'Certains liens vers les hôtels sont affiliés. Cela ne change ni le prix payé ni la sélection.',
  affiliateShort: 'Certains liens hôtels sont affiliés.',
  methodology: 'Méthodologie',
  quickAnswer: 'Réponse rapide',
  metres: 'm',
  closedOffSeason: 'Fermé hors saison',
  checkAvailability: 'Voir les disponibilités',
  seePage: 'Voir la page',
  inPreparation: 'Bientôt en ligne',
  open: 'Ouvert',
  reduced: 'Fermé en partie',
  closed: 'Fermé',
  months: ['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D'],
  choice: { village: 'Village', forWhom: 'Pour qui', legendFull: 'Carré plein = plus fort sur ce critère', legendBest: 'Meilleur choix du critère' },
  pass: { section: 'Section', coverage: 'Swiss Travel Pass', included: 'Inclus', discount25: '-25 %', discount50: '-50 %', fare: 'Tarif 2026 · CHF', without: 'Sans pass', with: 'Avec pass', withoutShort: 'Sans', withShort: 'Avec' },
  booking: { where: 'Où', checkin: 'Arrivée', checkout: 'Départ', search: 'Voir les hôtels', nights: 'nuits', trust: 'Vos dates s’appliquent à chaque hôtel et à la carte en direct.' },
  sell: {
    liveMap: 'Hôtels à {place}, prix en direct',
    liveMapSub: 'Choisissez vos dates plus haut, puis cliquez sur un repère pour voir le prix et réserver sur le site partenaire.',
    seeAll: 'Voir tous les hôtels à {place}',
    checkPrices: 'Voir les prix',
    stickyTitle: 'Hôtels à {place}',
    stickyCta: 'Voir les prix',
    ctaBandTitle: 'Votre secteur est choisi ? Voyez ce qui reste libre à {place}.',
    ctaBandText: 'Prix et disponibilités changent chaque jour dans les Alpes, surtout en juillet, en août et à Noël.',
    hotelsIn: 'Hôtels à {place}',
    moreForTrip: 'Pour aller plus loin',
    how: [
      { t: 'Choisir le bon village', d: 'Chaque page dit où dormir et pourquoi, avec les chiffres qui tranchent.' },
      { t: 'Comparer sur la carte', d: 'La carte en direct affiche les hébergements avec les prix pour vos dates.' },
      { t: 'Réserver chez le partenaire', d: 'Vous réservez sur Booking.com, Expedia ou d’autres, à leur prix. Nous pouvons toucher une commission.' },
    ],
    howTitle: 'Comment ça marche',
    featured: 'Guide à la une',
    readGuide: 'Lire le guide',
    popular: 'Recherches fréquentes',
    all: 'Tout',
    carFreeFilter: 'Sans voiture',
    close: 'Fermer',
    hotels: { all: 'Tous', tiers: { budget: 'Petit budget', mid: 'Milieu de gamme', premium: 'Haut de gamme' }, from: 'À partir de', perNight: '/ nuit', average: 'Moyenne relevée', seasonAvg: { summer: 'Moyenne en été', winter: 'Moyenne en hiver' }, noSeason: 'Aucun prix trouvé pour cette saison aux dates relevées', noPrice: 'Aucun prix relevé à nos dates témoins', cta: 'Voir les prix', stars: 'étoiles', title: '{count} hôtels à {place}, du petit budget au haut de gamme', note: 'Prix : tarif le plus bas et moyenne par nuit relevés sur Booking.com pour 2 adultes et 1 chambre, sur {winter} dates d’hiver et {summer} dates d’été, le {date}. Ils sont indicatifs : le vrai prix dépend de vos dates. Les faits sur les hôtels viennent de leur propre site.' },
    seasons: { summer: 'Été', winter: 'Hiver', title: 'Été ou hiver ?', base: 'Où dormir cette saison', sub: 'Choisissez une saison, ou vos dates plus haut : prix et conseils suivent.' },
    doing: { kinds: { walk: 'À pied', ride: 'En montagne', local: 'Typique d’ici', table: 'Où manger' } },
    onThisPage: { map: 'Carte', overview: 'En bref', hotels: 'Hôtels', areas: 'Secteurs', doing: 'Sur place', pass: 'Swiss Travel Pass', seasons: 'Saisons', carFree: 'Sans voiture', practical: 'Pratique', faq: 'FAQ', choice: 'Comparer', sheet: 'Villages', verdict: 'Verdict' },
  },
  mapNote: 'Carte fournie par Stay22. Les réservations effectuées depuis cette carte peuvent générer une commission.',
  mapLoad: 'Afficher la carte',
  footer: {
    regions: 'Régions',
    destinations: 'Destinations',
    guides: 'Guides pratiques',
    about: 'À propos',
    affiliation: 'Affiliation',
    legal: 'Mentions légales',
    privacy: 'Confidentialité et cookies',
    independent: 'Guide indépendant, sans lien avec les autorités suisses ni avec Suisse Tourisme.',
  },
  notFound: { title: 'Page introuvable', text: "Cette page n'existe pas ou a changé d'adresse.", home: "Retour à l'accueil" },
}

const de: Dict = {
  nav: { destinations: 'Reiseziele', regions: 'Regionen', carFree: 'Autofrei', pass: 'Swiss Travel Pass', carRental: 'Mietwagen', menu: 'Menü', close: 'Schliessen' },
  affiliate: 'Einige Hotel-Links sind Affiliate-Links. Das ändert weder Ihren Preis noch unsere Auswahl.',
  affiliateShort: 'Einige Hotel-Links sind Affiliate-Links.',
  methodology: 'Methodik',
  quickAnswer: 'Kurze Antwort',
  metres: 'm',
  closedOffSeason: 'Zwischensaison geschlossen',
  checkAvailability: 'Verfügbarkeit prüfen',
  seePage: 'Zur Seite',
  inPreparation: 'Demnächst online',
  open: 'Offen',
  reduced: 'Teilweise geschlossen',
  closed: 'Geschlossen',
  months: ['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D'],
  choice: { village: 'Ort', forWhom: 'Für wen', legendFull: 'Volles Quadrat = stärker bei diesem Kriterium', legendBest: 'Beste Wahl für das Kriterium' },
  pass: { section: 'Strecke', coverage: 'Swiss Travel Pass', included: 'Inbegriffen', discount25: '-25 %', discount50: '-50 %', fare: 'Tarif 2026 · CHF', without: 'Ohne Pass', with: 'Mit Pass', withoutShort: 'Ohne', withShort: 'Mit' },
  booking: { where: 'Wohin', checkin: 'Anreise', checkout: 'Abreise', search: 'Hotels ansehen', nights: 'Nächte', trust: 'Ihre Daten gelten für jedes Hotel und die Live-Karte.' },
  sell: {
    liveMap: 'Hotels in {place}, Live-Preise',
    liveMapSub: 'Oben Daten wählen, dann auf eine Markierung klicken, um den Preis zu sehen und beim Partner zu buchen.',
    seeAll: 'Alle Hotels in {place}',
    checkPrices: 'Preise prüfen',
    stickyTitle: 'Hotels in {place}',
    stickyCta: 'Preise ansehen',
    ctaBandTitle: 'Ortsteil gewählt? Prüfen Sie, was in {place} noch frei ist.',
    ctaBandText: 'Preise und Verfügbarkeit ändern sich in den Alpen täglich, besonders im Juli, August und über Weihnachten.',
    hotelsIn: 'Hotels in {place}',
    moreForTrip: 'Mehr für Ihre Reise',
    how: [
      { t: 'Den richtigen Ort wählen', d: 'Jede Seite sagt, wo Sie übernachten und warum, mit den entscheidenden Zahlen.' },
      { t: 'Auf der Karte vergleichen', d: 'Die Live-Karte zeigt die Unterkünfte mit Preisen für Ihre Daten.' },
      { t: 'Beim Partner buchen', d: 'Sie buchen bei Booking.com, Expedia oder anderen zu deren Preis. Wir erhalten eventuell eine Provision.' },
    ],
    howTitle: "So funktioniert's",
    featured: 'Ratgeber im Fokus',
    readGuide: 'Zum Ratgeber',
    popular: 'Häufige Suchen',
    all: 'Alle',
    carFreeFilter: 'Autofrei',
    close: 'Schliessen',
    hotels: { all: 'Alle', tiers: { budget: 'Günstig', mid: 'Mittelklasse', premium: 'Gehoben' }, from: 'Ab', perNight: '/ Nacht', average: 'Durchschnitt', seasonAvg: { summer: 'Durchschnitt Sommer', winter: 'Durchschnitt Winter' }, noSeason: 'Für diese Saison an unseren Stichtagen kein Preis gefunden', noPrice: 'An unseren Stichtagen kein Preis erhoben', cta: 'Preise prüfen', stars: 'Sterne', title: '{count} Hotels in {place}, von günstig bis gehoben', note: 'Preise: tiefster und durchschnittlicher Nachtpreis auf Booking.com für 2 Erwachsene und 1 Zimmer, an {winter} Winter- und {summer} Sommerdaten, erhoben am {date}. Richtwerte: der echte Preis hängt von Ihren Daten ab. Hotelfakten stammen von der Website des jeweiligen Hotels.' },
    seasons: { summer: 'Sommer', winter: 'Winter', title: 'Sommer oder Winter?', base: 'Wo wohnen in dieser Saison', sub: 'Saison wählen oder oben Daten eingeben: Preise und Tipps passen sich an.' },
    doing: { kinds: { walk: 'Zu Fuss', ride: 'Am Berg', local: 'Typisch hier', table: 'Wo essen' } },
    onThisPage: { map: 'Karte', overview: 'Überblick', hotels: 'Hotels', areas: 'Ortsteile', doing: 'Vor Ort', pass: 'Swiss Travel Pass', seasons: 'Saisons', carFree: 'Autofrei', practical: 'Praktisch', faq: 'FAQ', choice: 'Vergleich', sheet: 'Orte', verdict: 'Empfehlung' },
  },
  mapNote: 'Karte von Stay22. Buchungen über diese Karte können uns eine Provision einbringen.',
  mapLoad: 'Karte anzeigen',
  footer: {
    regions: 'Regionen',
    destinations: 'Reiseziele',
    guides: 'Praktische Ratgeber',
    about: 'Über uns',
    affiliation: 'Affiliate-Links',
    legal: 'Impressum',
    privacy: 'Datenschutz und Cookies',
    independent: 'Unabhängiger Reiseführer, ohne Verbindung zu den Schweizer Behörden oder Schweiz Tourismus.',
  },
  notFound: { title: 'Seite nicht gefunden', text: 'Diese Seite existiert nicht oder wurde verschoben.', home: 'Zur Startseite' },
}

const dicts: Record<Locale, Dict> = { en, fr, de }

export const getDict = (locale: Locale): Dict => dicts[locale]

/** Fill {place} style tokens. */
export const fill = (template: string, vars: Record<string, string>) => template.replace(/\{(\w+)\}/g, (_, k) => vars[k] ?? '')
